#!/bin/bash


set -o errexit
set -o pipefail
set -o nounset

export BUILDKITE_BUILD_ID=build-test
export BUILDKITE_AGENT_ACCESS_TOKEN=BUILDKITE_AGENT_ACCESS_TOKEN
export BUILDKITE_COMMAND="./node_libraries/hash_checker create-corejs player-auth player-graphdb pubsub-synchronizer redis-discovery redis-distributed-chunker"
export BUILDKITE_PLUGIN_SMART_CI_ENTRYPOINT="sh -c"
export BUILDKITE_PLUGIN_SMART_CI_DEBUG=true
export BUILDKITE_PLUGIN_SMART_CI_IMAGE=BUILDKITE_PLUGIN_SMART_CI_IMAGE
export BUILDKITE_PLUGIN_SMART_CI_MOUNT_BUILDKITE_AGENT=false
export BUILDKITE_PLUGIN_SMART_CI_HOOKS_ENVIRONMENT=true

./hooks/command